// src/app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "@digdir/designsystemet-css/index.css";
import "../../design-tokens-build/brand-1.css"; 
import "./globals.css";


import { ThemeManager } from "../../src/app/components/ThemeManager"; 
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log("[Server] RootLayout rendering on server");



  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/vmx5jgv.css" />
      </head>
      <body className={inter.className}>
        {children}
        <ThemeManager /> 
      </body>
    </html>
  );
}
