import type { HeaderSearchItem } from './index';

/**
 * Story fixture for the Header's search: the 91 entries the old docs site
 * indexed (pages, components, articles), reduced to what the Header needs.
 * A fixture rather than real data because the library ships no search index;
 * consumers pass their own items. Kept complete so the search stories and
 * their visual baselines stay exactly as they were when the docs site left
 * this repo.
 */
export const searchItemsFixture: HeaderSearchItem[] = [
  { id: 'home', title: 'Hjem', path: 'home' },
  { id: 'components', title: 'Komponenter', path: 'components' },
  { id: 'whats-new', title: 'Hva er nytt', path: 'whats-new' },
  { id: 'design', title: 'Design', path: 'design' },
  { id: 'designretning', title: 'Designretning', path: 'designretning' },
  { id: 'code', title: 'Kode', path: 'code' },
  { id: 'tokens', title: 'Tokens', path: 'tokens' },
  { id: 'alert', title: 'Alert', path: 'components/alert' },
  { id: 'avatar', title: 'Avatar', path: 'components/avatar' },
  { id: 'badge', title: 'Badge', path: 'components/badge' },
  { id: 'breadcrumbs', title: 'Breadcrumbs', path: 'components/breadcrumbs' },
  { id: 'button', title: 'Button', path: 'components/button' },
  { id: 'card', title: 'Card', path: 'components/card' },
  { id: 'carousel', title: 'Carousel', path: 'components/carousel' },
  { id: 'checkbox', title: 'Checkbox', path: 'components/checkbox' },
  { id: 'chip', title: 'Chip', path: 'components/chip' },
  { id: 'dateinput', title: 'DateInput', path: 'components/dateinput' },
  { id: 'datepicker', title: 'DatePicker', path: 'components/datepicker' },
  { id: 'details', title: 'Details', path: 'components/details' },
  { id: 'dialog', title: 'Dialog', path: 'components/dialog' },
  { id: 'divider', title: 'Divider', path: 'components/divider' },
  { id: 'donor', title: 'Donor', path: 'components/donor' },
  { id: 'dropdown', title: 'Dropdown', path: 'components/dropdown' },
  { id: 'errorsummary', title: 'ErrorSummary', path: 'components/errorsummary' },
  { id: 'field', title: 'Field', path: 'components/field' },
  { id: 'fieldset', title: 'Fieldset', path: 'components/fieldset' },
  { id: 'footer', title: 'Footer', path: 'components/footer' },
  { id: 'graphicelement', title: 'GraphicElement', path: 'components/graphicelement' },
  { id: 'header', title: 'Header', path: 'components/header' },
  { id: 'heading', title: 'Heading', path: 'components/heading' },
  { id: 'input', title: 'Input', path: 'components/input' },
  { id: 'label', title: 'Label', path: 'components/label' },
  { id: 'link', title: 'Link', path: 'components/link' },
  { id: 'list', title: 'List', path: 'components/list' },
  { id: 'pagination', title: 'Pagination', path: 'components/pagination' },
  { id: 'paragraph', title: 'Paragraph', path: 'components/paragraph' },
  { id: 'popover', title: 'Popover', path: 'components/popover' },
  { id: 'radio', title: 'Radio', path: 'components/radio' },
  { id: 'search', title: 'Search', path: 'components/search' },
  { id: 'select', title: 'Select', path: 'components/select' },
  { id: 'skeletonloader', title: 'SkeletonLoader', path: 'components/skeletonloader' },
  { id: 'skiplink', title: 'SkipLink', path: 'components/skiplink' },
  { id: 'spinnerloader', title: 'SpinnerLoader', path: 'components/spinnerloader' },
  { id: 'suggestion', title: 'Suggestion', path: 'components/suggestion' },
  { id: 'switch', title: 'Switch', path: 'components/switch' },
  { id: 'table', title: 'Table', path: 'components/table' },
  { id: 'tabs', title: 'Tabs', path: 'components/tabs' },
  { id: 'tag', title: 'Tag', path: 'components/tag' },
  { id: 'textarea', title: 'Textarea', path: 'components/textarea' },
  { id: 'textfield', title: 'Textfield', path: 'components/textfield' },
  { id: 'togglegroup', title: 'ToggleGroup', path: 'components/togglegroup' },
  { id: 'tooltip', title: 'Tooltip', path: 'components/tooltip' },
  { id: 'validationmessage', title: 'ValidationMessage', path: 'components/validationmessage' },
  { id: 'designretning-varm', title: 'Varm — farger og typografi', path: 'designretning/varm' },
  { id: 'designretning-rod-trad', title: 'Rød tråd (kors)', path: 'designretning/rod-trad' },
  { id: 'designretning-mennesker', title: 'Mennesker i fokus', path: 'designretning/mennesker-i-fokus' },
  { id: 'designretning-sosial', title: 'Sosial tilstedeværelse', path: 'designretning/sosial-tilstedevaerelse' },
  { id: 'designretning-framdrift', title: 'Framdrift og effekt', path: 'designretning/framdrift-og-effekt' },
  { id: 'figma-oppkobling', title: 'Figma tilkobling', path: 'design/figma-oppkobling' },
  { id: 'oppstart', title: 'Oppstart', path: 'design/oppstart' },
  { id: 'lage-komponenter', title: 'Lage en ny komponent', path: 'design/lage-komponenter' },
  { id: 'praktiske-eksempler', title: 'Praktiske eksempler', path: 'design/praktiske-eksempler' },
  { id: 'token-studio', title: 'Token Studio', path: 'design/token-studio' },
  { id: 'fargesystem', title: 'Sette opp ditt eget fargesystem', path: 'design/fargesystem' },
  { id: 'temabygger', title: 'Temabygger', path: 'design/temabygger' },
  { id: 'bruk-farger', title: 'Bruk fargene', path: 'design/bruk-farger' },
  { id: 'vedlikeholde-design-tokens', title: 'Vedlikeholde design tokens', path: 'design/vedlikeholde-design-tokens' },
  { id: 'endre-bygge-tema', title: 'Endre og bygge tema', path: 'design/endre-bygge-tema' },
  { id: 'koble-tokens-til-figma', title: 'Koble tokens til Figma', path: 'design/koble-tokens-til-figma' },
  { id: 'foresla-design', title: 'Foreslå nytt design', path: 'design/foresla-design' },
  { id: 'hva-er-design-tokens', title: 'Hva er design tokens', path: 'design/hva-er-design-tokens' },
  { id: 'design-tokens-i-figma', title: 'Design tokens i Figma', path: 'design/design-tokens-i-figma' },
  { id: 'farger-navnestruktur', title: 'Farger: Navnestruktur', path: 'design/farger-navnestruktur' },
  { id: 'farger-oversikt', title: 'Farger: Oversikt', path: 'design/farger-oversikt' },
  { id: 'farge-tokens', title: 'Farge-tokens', path: 'design/farge-tokens' },
  { id: 'skygger-bruk', title: 'Bruk av skygger', path: 'design/skygger-bruk' },
  { id: 'skygge-tokens', title: 'Skygge-tokens', path: 'design/skygge-tokens' },
  { id: 'komponent-storrelser', title: 'Komponentstørrelser', path: 'design/komponent-storrelser' },
  { id: 'storrelse-tokens', title: 'Størrelse-tokens', path: 'design/storrelse-tokens' },
  { id: 'font-family', title: 'Typografi: Font-family', path: 'design/font-family' },
  { id: 'typografi-tokens', title: 'Typografi-tokens', path: 'design/typografi-tokens' },
  { id: 'kom-i-gang', title: 'Kom i gang (Kode)', path: 'code/kom-i-gang' },
  { id: 'code-design-tokens', title: 'Design tokens (Kode)', path: 'code/design-tokens' },
  { id: 'fonts', title: 'Fonter', path: 'code/fonts' },
  { id: 'icons', title: 'Ikoner', path: 'code/icons' },
  { id: 'contributing', title: 'Bidra med kode', path: 'code/contributing' },
  { id: 'figma-mcp-intro', title: 'Fra Figma til kode (MCP)', path: 'code/figma-mcp-intro' },
  { id: 'figma-mcp-cursor', title: 'Figma MCP i Cursor', path: 'code/figma-mcp-cursor' },
  { id: 'figma-mcp-claude', title: 'Figma MCP i Claude', path: 'code/figma-mcp-claude' },
  { id: 'komponent-kreasjon', title: 'Komponentkreasjon', path: 'code/komponent-kreasjon' },
  { id: 'metadata-files', title: 'Metadata-filer', path: 'code/metadata-files' },
];
