name: Build and Deploy Storybook

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install dependencies
        run: npm ci

      - name: Update design tokens package
        run: npm update rk-design-tokens

      - name: Commit and Push Dependency Updates
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(deps): update rk-design-tokens to latest"
      
      - name: Build package
        run: npm run build

      - name: Bump version and publish to npm
        run: |
          npm version patch --no-git-tag-version
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Commit version bump
        run: |
          git add package.json package-lock.json
          git commit -m "chore(release): bump version to $(node -p "require('./package.json').version")" || true
          git push origin main

      - name: Build Storybook
        run: npm run build-storybook

      - name: Copy Metadata
        run: cp metadata.json storybook-build/metadata.json

      - name: Deploy to GitHub Pages
        run: |
          npx gh-pages \
            --repo https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}.git \
            --dest storybook \
            -d storybook-build